@startuml gab
left to right direction
skinparam packageStyle rectangle


actor PorteurCarte <<Humain>>
actor ClientBanque <<Humain>>
actor OpérateurMaintenance <<(Interne) Humain>>
actor SIBanque <<Non Humain>>
actor SAVisa <<Non Humain>>


rectangle GAB {
    (Déposer des chèques) as (dpdc)


    PorteurCarte <|-- ClientBanque
    PorteurCarte -- (Rétirer de l'argent)
    ClientBanque -- (Consulter Solde)
    ClientBanque -- (Déposer du numéraire)
    ClientBanque -- (dpdc)
    (Recharger le distributeur) -- OpérateurMaintenance
    (Récuperer les cartes avalées) -- OpérateurMaintenance
    (Récuperer les chèques) -- OpérateurMaintenance
    (dpdc) -- SIBanque
    (Rétirer de l'argent) -- SIBanque
    (Consulter Solde) -- SIBanque
    (Déposer du numéraire) -- SIBanque
    (Rétirer de l'argent) -- SAVisa

}


@enduml