@startuml gab
left to right direction
skinparam packageStyle rectangle


actor PorteurCarte <<Humain>>
actor ClientBanque <<Humain>>
actor OpérateurMaintenance <<(Interne) Humain>>
actor SIBanque <<Non Humain>>
actor SAVisa <<Non Humain>>


rectangle GAB {
    (Déposer des chèques) as (depcheq)
    (S'authentifier) as (auth)
    (Rétirer de l'argent \navec une carte visa) as (withdrawVisa)
    (Rétirer de l'argent \navec une carte bancaire) as (withdrawCB)
    (Déposer du numéraire) as (depnum)
    (Consulter Solde) as (consult)


    PorteurCarte <|-- ClientBanque
    PorteurCarte -- (withdrawVisa)

    ClientBanque -- (Consulter Solde)
    ClientBanque -- (depnum)
    ClientBanque -- (depcheq)
    ClientBanque -- (auth)


    (Recharger le distributeur) -- OpérateurMaintenance
    (Récuperer les cartes avalées) -- OpérateurMaintenance
    (Récuperer les chèques) -- OpérateurMaintenance


    (depcheq) -- SIBanque
    (withdrawVisa) -- SIBanque
    (Consulter Solde) -- SIBanque
    (depnum) -- SIBanque


    (withdrawVisa) -- SAVisa

}

newpage

rectangle GAB {
    (Déposer des chèques) as (depcheq)
    (S'authentifier) as (auth)
    (Rétirer de l'argent \navec une carte visa) as (withdrawVisa)
    (Rétirer de l'argent \navec une carte bancaire) as (withdrawCB)
    (Déposer du numéraire) as (depnum)
    (Consulter Solde) as (consult)

    (withdrawCB) .> (auth) : <<inclut>>
    (auth) <.down. (withdrawVisa) : <<inclut>>
    (depnum) .up.> (auth) : <<inclut>>
    (auth) <.up. (depcheq) : <<inclut>>
    (consult) .left.> (auth) : <<inclut>>
}

@enduml